- name: check if running on cloud
  stat:
    path: /var/lib/cloud
  register: cloud

- name: Wait for updates / upgrades from user data script to release lock
  script: wait-for-apt-on-startup.sh
  when: cloud.stat.exists

- name: Install JQ
  apt:
    name: jq
    state: present
    update_cache: yes