---
- hosts: all
  become: yes
  tasks:
    - include_role:
        name: insight_infra.cloud_helper
      vars:
        enable_cloud_wait: true
        enable_jq: true
    - include_role:
        name: node-exporter
      when: prometheus_enabled|bool
    - include_role:
        name: brianshumate.consul
      vars:
        consul_group_name: "all"
        consul_version: 1.7.2
        consul_encrypt_enable: false
        consul_config_custom:
          retry_join:
            - "{{ retry_join_string }}"
      when: consul_enabled|bool
    - include_role:
        name: consul-cleanup
      when: consul_enabled|bool
    - include_role:
        name: insight_w3f.polkadot_library
    - include_role:
        name: insight_w3f.polkadot_health_check