---
- hosts: all
  become: yes
  roles:
    - google-cloud

- hosts: all
  become: yes
  strategy: free
  roles:
    - node-exporter
    - polkadot-common

- hosts: all
  become: yes
  roles:
    - common
    - polkadot-public
    - health-check